name: Android CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      env:
        SENSORICS_FABRIC_KEY: ${{ secrets.SENSORICS_FABRIC_KEY }}
      run: ./gradlew -Psensorics_fabricKey=${SENSORICS_FABRIC_KEY} test

  assemble_debug:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Assemble with Gradle
      env:
        SENSORICS_FABRIC_KEY: ${{ secrets.SENSORICS_FABRIC_KEY }}
      run: ./gradlew -Psensorics_fabricKey=${SENSORICS_FABRIC_KEY} assembleDebug
    - name: Archive assembled artifacts
      uses: actions/upload-artifact@v1
      with:
          name: artifacts
          path: ./app/build/outputs

