name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      env:
        SENSORICS_FABRIC_KEY: ${{ secrets.SENSORICS_FABRIC_KEY }}
      run: ./gradlew -Psensorics_fabricKey=${SENSORICS_FABRIC_KEY} test
